spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:postgresql://localhost:5432/polet
#    username: polet
#    password: polet
#    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
logging:
  level:
    root: info
    liquibase: debug
vinmonopolet:
  encoding: windows-1252
  url: https://apis.vinmonopolet.no
  apiKey: ""
server:
  port: 8000
