spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polet
    username: polet
    password: polet
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

logging:
  level:
    root: info
    liquibase: debug
vinmonopolet:
  url: https://apis.vinmonopolet.no
  apiKey: ""
server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
#http://localhost:8000/h2-console

  flyway:
    locations: classpath:/db/migration,/db/data